apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: thy8v2mac-java-springboot
  janus-idp.io/tekton: thy8v2mac-java-springboot
  backstage.io/kubernetes-id: thy8v2mac-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: thy8v2mac-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
